/* RENESAS OPTIMIZING LINKER GENERATED FILE 2021.05.16 */
/*** variable information ***/
#pragma saddr crc_time_tick /* count:40,size:4,near,crc_cfg.obj */
#pragma saddr p_uart_two /* count:14,size:2,near,uart_cfg.obj */
#pragma saddr p_uart_three /* count:14,size:2,near,uart_cfg.obj */
#pragma saddr g_system_core_clock /* count:20,size:4,near,rl78_cfg.obj */
#pragma saddr g_crc_enable /* count:4,size:1,near,crc_cfg.obj */
#pragma saddr gpio_time_tick /* count:16,size:4,near,gpio_cfg.obj */
#pragma saddr p_ms1022_one /* count:7,size:2,near,ms1022_cfg.obj */
#pragma saddr p_sys_tick_one /* count:6,size:2,near,sys_tick_cfg.obj */
#pragma saddr gp_uart1_tx_address /* count:3,size:2,near,r_cg_sau.obj */
#pragma saddr g_uart1_tx_count /* count:2,size:2,near,r_cg_sau.obj */
#pragma saddr gp_csi00_tx_address /* count:3,size:2,near,r_cg_sau.obj */
#pragma saddr g_csi00_tx_count /* count:2,size:2,near,r_cg_sau.obj */
#pragma saddr gp_uart2_tx_address /* count:3,size:2,near,r_cg_sau.obj */
#pragma saddr g_uart2_tx_count /* count:2,size:2,near,r_cg_sau.obj */
#pragma saddr p_at24cxx_one /* count:3,size:2,near,at24cxx_cfg.obj */
#pragma saddr gp_uart1_rx_address /* count:1,size:2,near,r_cg_sau.obj */
#pragma saddr g_uart1_rx_count /* count:1,size:2,near,r_cg_sau.obj */
#pragma saddr g_uart1_rx_length /* count:1,size:2,near,r_cg_sau.obj */
#pragma saddr gp_csi00_rx_address /* count:1,size:2,near,r_cg_sau.obj */
/* #pragma saddr g_csi00_rx_length */ /* count:0,size:2,near,unref,r_cg_sau.obj */
/* #pragma saddr g_csi00_rx_count */ /* count:0,size:2,near,unref,r_cg_sau.obj */
/* #pragma saddr g_csi00_send_length */ /* count:0,size:2,near,unref,r_cg_sau.obj */
#pragma saddr gp_uart2_rx_address /* count:1,size:2,near,r_cg_sau.obj */
#pragma saddr g_uart2_rx_count /* count:1,size:2,near,r_cg_sau.obj */
#pragma saddr g_uart2_rx_length /* count:1,size:2,near,r_cg_sau.obj */
#pragma saddr p_uart_rx_buffer_two /* count:1,size:2,near,uart_cfg.obj */
#pragma saddr p_uart_tx_buffer_two /* count:1,size:2,near,uart_cfg.obj */
#pragma saddr p_uart_rx_buffer_three /* count:1,size:2,near,uart_cfg.obj */
#pragma saddr p_uart_tx_buffer_three /* count:1,size:2,near,uart_cfg.obj */
#pragma saddr temp_buffer /* count:1,size:4,near,main.obj */
/* #pragma saddr g_version_time */ /* count:0,size:9,near,unref,const,complier_cfg.obj */
/* #pragma saddr g_version_date */ /* count:0,size:12,near,unref,const,complier_cfg.obj */
#pragma saddr g_sys_tick_one /* count:1,size:12,near,sys_tick_cfg.obj */
/* #pragma saddr g_month_days_table */ /* count:0,size:13,near,unref,const,rtc_cfg.obj */
#pragma saddr g_uart_two /* count:1,size:52,near,uart_cfg.obj */
#pragma saddr g_uart_three /* count:1,size:52,near,uart_cfg.obj */
/* #pragma saddr g_ms1022_one */ /* count:1,size:84,near,ms1022_cfg.obj */
/* #pragma saddr g_uart_rx_buffer_three */ /* count:1,size:96,near,uart_cfg.obj */
/* #pragma saddr g_uart_tx_buffer_three */ /* count:1,size:96,near,uart_cfg.obj */
/* #pragma saddr g_at24cxx_one */ /* count:1,size:164,near,at24cxx_cfg.obj */
/* #pragma saddr g_uart_rx_buffer_two */ /* count:1,size:274,near,uart_cfg.obj */
/* #pragma saddr g_uart_tx_buffer_two */ /* count:1,size:274,near,uart_cfg.obj */
/* #pragma saddr g_Dmac0 */ /* count:1,size:1024,near,r_cg_dmac.obj */

/*** function information ***/
#pragma callt gpio_pin_set /* count:69,far,gpio_cfg.obj */
#pragma callt gpio_pin_reset /* count:56,far,gpio_cfg.obj */
#pragma callt sys_tick_task_get_tick /* count:29,far,sys_tick_task.obj */
#pragma callt gpio_task_pin_mode_output /* count:20,far,gpio_task.obj */
#pragma callt gpio_task_pin_mode_input /* count:19,far,gpio_task.obj */
#pragma callt wdt_task_restart /* count:17,far,wdt_task.obj */
#pragma callt ms1022_spi_send_reg /* count:15,far,ms1022_cfg.obj */
#pragma callt delay_task_us /* count:14,far,delay_task.obj */
#pragma callt i2c_task_msw_start /* count:13,far,i2c_task.obj */
#pragma callt i2c_task_msw_read_ack /* count:12,far,i2c_task.obj */
#pragma callt i2c_task_msw_send_byte /* count:12,far,i2c_task.obj */
#pragma callt gpio_pin_read /* count:12,far,gpio_cfg.obj */
#pragma callt app_get_tick /* count:11,far,main.obj */
#pragma callt gpio_task_pin_mode_pull_up_set /* count:8,far,gpio_task.obj */
#pragma callt i2c_task_msw_stop /* count:7,far,i2c_task.obj */
#pragma callt delay_task_ms /* count:7,far,delay_task.obj */
#pragma callt gpio_task_pin_set /* count:6,far,gpio_task.obj */
#pragma callt gpio_pin_mode_set /* count:6,far,gpio_cfg.obj */
#pragma callt gpio_pin_mode_reset /* count:6,far,gpio_cfg.obj */
#pragma callt ms1022_spi_byte_buffer /* count:6,far,ms1022_cfg.obj */
#pragma callt spi_msw_bit_msb_word /* count:6,far,spi_cfg.obj */
#pragma callt spi_msw_bit_lsb_word /* count:6,far,spi_cfg.obj */
/* #pragma callt ms1022_spi_send_cmd */ /* count:6,far,ms1022_cfg.obj */
/* #pragma callt uart_wait_send_idle */ /* count:6,far,uart_cfg.obj */
/* #pragma callt i2c_msw_send_byte */ /* count:5,far,i2c_cfg.obj */
/* #pragma callt i2c_msw_read_ack */ /* count:5,far,i2c_cfg.obj */
/* #pragma callt at24cxx_sw_i2c_read_page_byte */ /* count:5,far,at24cxx_cfg.obj */
/* #pragma callt at24cxx_sw_i2c_send_page_byte */ /* count:5,far,at24cxx_cfg.obj */
/* #pragma callt gpio_task_pin_mode_digital */ /* count:4,far,gpio_task.obj */
/* #pragma callt delay_clk_nop */ /* count:4,far,delay_cfg.obj */
/* #pragma callt spi_msw_bit_msb_byte */ /* count:4,far,spi_cfg.obj */
/* #pragma callt spi_msw_bit_lsb_byte */ /* count:4,far,spi_cfg.obj */
/* #pragma callt i2c_lib_msw_start */ /* count:4,far,i2c_lib.obj */
/* #pragma callt i2c_msw_stop */ /* count:4,far,i2c_cfg.obj */
/* #pragma callt at24cxx_sw_i2c_send_single_byte */ /* count:4,far,at24cxx_cfg.obj */
/* #pragma callt crc_crc8_type */ /* count:3,far,crc_cfg.obj */
/* #pragma callt crc_crc16_type */ /* count:3,far,crc_cfg.obj */
/* #pragma callt i2c_task_msw_send_ack */ /* count:3,far,i2c_task.obj */
/* #pragma callt i2c_task_msw_read_byte */ /* count:3,far,i2c_task.obj */
/* #pragma callt delay_task_nop */ /* count:3,far,delay_task.obj */
/* #pragma callt gpio_pin_toggle */ /* count:3,far,gpio_cfg.obj */
/* #pragma callt uart_send_reset */ /* count:3,far,uart_cfg.obj */
/* #pragma callt uart_read_reset */ /* count:3,far,uart_cfg.obj */
/* #pragma callt crc_check_sum_type */ /* count:3,far,crc_cfg.obj */
/* #pragma callt spi_msw_msb_word_cmd */ /* count:3,far,spi_cfg.obj */
/* #pragma callt spi_msw_lsb_word_cmd */ /* count:3,far,spi_cfg.obj */
/* #pragma callt rl78_perpheral_clock_enable */ /* count:3,far,rl78_cfg.obj */
/* #pragma callt i2c_msw_send_bit */ /* count:3,far,i2c_cfg.obj */
/* #pragma callt spi_msw_read_msb_byte */ /* count:3,far,spi_cfg.obj */
/* #pragma callt i2c_msw_start */ /* count:3,far,i2c_cfg.obj */
/* #pragma callt gpio_wait_time */ /* count:3,far,gpio_cfg.obj */
/* #pragma callt at24cxx_sw_i2c_read_single_byte */ /* count:3,far,at24cxx_cfg.obj */
/* #pragma callt crc_crc32_type */ /* count:2,far,crc_cfg.obj */
/* #pragma callt uart_task_read_reset */ /* count:2,far,uart_task.obj */
/* #pragma callt uart_task_read_end */ /* count:2,far,uart_task.obj */
/* #pragma callt uart_task_init */ /* count:2,far,uart_task.obj */
/* #pragma callt uart_task_fill_mode_send_two */ /* count:2,far,uart_task.obj */
/* #pragma callt spi_lib_msw_read_msb_byte */ /* count:2,far,spi_lib.obj */
/* #pragma callt i2c_msw_send_ack */ /* count:2,far,i2c_cfg.obj */
/* #pragma callt gpio_read */ /* count:2,far,gpio_cfg.obj */
/* #pragma callt delay_n_us */ /* count:2,far,delay_cfg.obj */
/* #pragma callt delay_nop */ /* count:2,far,delay_cfg.obj */
/* #pragma callt uart_it_irq_read_error_handle_two */ /* count:2,far,uart_cfg.obj */
/* #pragma callt uart_it_irq_read_error_handle_three */ /* count:2,far,uart_cfg.obj */
/* #pragma callt ascii_to_utf8_byte */ /* count:2,far,complier_lib.obj */
/* #pragma callt spi_msw_msb_byte_cmd */ /* count:2,far,spi_cfg.obj */
/* #pragma callt spi_msw_lsb_byte_cmd */ /* count:2,far,spi_cfg.obj */
/* #pragma callt uart_it_irq_send_handle_two */ /* count:2,far,uart_cfg.obj */
/* #pragma callt uart_it_irq_send_handle_three */ /* count:2,far,uart_cfg.obj */
/* #pragma callt gpio_time_tick_init */ /* count:2,far,gpio_cfg.obj */
/* #pragma callt crc_init */ /* count:2,far,crc_cfg.obj */
/* #pragma callt i2c_msw_deinit */ /* count:2,far,i2c_cfg.obj */
/* #pragma callt i2c_msw_ack */ /* count:2,far,i2c_cfg.obj */
/* #pragma callt i2c_msw_nack */ /* count:2,far,i2c_cfg.obj */
/* #pragma callt spi_msw_send_msb_byte */ /* count:2,far,spi_cfg.obj */
/* #pragma callt spi_msw_send_lsb_byte */ /* count:2,far,spi_cfg.obj */
/* #pragma callt i2c_msw_read_byte */ /* count:2,far,i2c_cfg.obj */
/* #pragma callt spi_msw_send_msb_word_buffer */ /* count:2,far,spi_cfg.obj */
/* #pragma callt spi_msw_read_msb_word_buffer */ /* count:2,far,spi_cfg.obj */
/* #pragma callt spi_msw_send_lsb_word_buffer */ /* count:2,far,spi_cfg.obj */
/* #pragma callt spi_msw_read_lsb_word_buffer */ /* count:2,far,spi_cfg.obj */
/* #pragma callt uart_fill_mode_send_start_two */ /* count:2,far,uart_cfg.obj */
/* #pragma callt uart_fill_mode_send_start_three */ /* count:2,far,uart_cfg.obj */
/* #pragma callt uart_fill_mode_send_two */ /* count:2,far,uart_cfg.obj */
/* #pragma callt uart_fill_mode_send_three */ /* count:2,far,uart_cfg.obj */
/* #pragma callt uart_it_irq_read_handle_three */ /* count:2,far,uart_cfg.obj */
/* #pragma callt uart_it_irq_read_handle_two */ /* count:2,far,uart_cfg.obj */
/* #pragma callt gpio_read_level_wait_time */ /* count:2,far,gpio_cfg.obj */
/* #pragma callt sys_tick_wait_us */ /* count:2,far,sys_tick_cfg.obj */
/* #pragma callt crc_check_sum_special */ /* count:2,far,crc_cfg.obj */
/* #pragma callt crc_check_sum_normal */ /* count:2,far,crc_cfg.obj */
/* #pragma callt uart_fill_mode_send_one */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_fill_mode_send_start_one */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_it_irq_read_handle_one */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_it_irq_read_error_handle_one */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_it_irq_send_handle_one */ /* count:1,far,uart_cfg.obj */
/* #pragma callt wdt_init */ /* count:1,far,wdt_cfg.obj */
/* #pragma callt delay_us */ /* count:1,far,delay_cfg.obj */
/* #pragma callt delay_ms */ /* count:1,far,delay_cfg.obj */
/* #pragma callt delay_s */ /* count:1,far,delay_cfg.obj */
/* #pragma callt gpio_init */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt crc_crc8_table */ /* count:1,far,crc_cfg.obj */
/* #pragma callt crc_crc16_table */ /* count:1,far,crc_cfg.obj */
/* #pragma callt crc_crc16_table_seed_data */ /* count:1,far,crc_cfg.obj */
/* #pragma callt spi_lib_msw_read_lsb_byte */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_task_msw_read_lsb_byte */ /* count:1,far,spi_task.obj */
/* #pragma callt at24cxx_i2c_send_single_byte */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt at24cxx_i2c_read_single_byte */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt i2c_master_deinit */ /* count:1,far,i2c_cfg.obj */
/* #pragma callt crc_crc32_crc */ /* count:1,far,crc_cfg.obj */
/* #pragma callt at24cxx_i2c_deinit */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt at24cxx_lib_i2c_time_tick_init */ /* count:1,far,at24cxx_lib.obj */
/* #pragma callt at24cxx_lib_i2c_deinit */ /* count:1,far,at24cxx_lib.obj */
/* #pragma callt at24cxx_lib_i2c_send_single_byte */ /* count:1,far,at24cxx_lib.obj */
/* #pragma callt at24cxx_lib_i2c_read_single_byte */ /* count:1,far,at24cxx_lib.obj */
/* #pragma callt i2c_lib_msw_deinit */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_lib_msw_stop */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_lib_msw_read_ack */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_lib_msw_send_ack */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_lib_msw_send_byte */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_lib_msw_send_word */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_lib_msw_read_byte */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_lib_msw_check_device */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_lib_msw_send_cmd */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_lib_master_deinit */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_lib_time_tick_init */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_task_msw_deinit */ /* count:1,far,i2c_task.obj */
/* #pragma callt i2c_task_time_tick_init */ /* count:1,far,i2c_task.obj */
/* #pragma callt delay_lib_nop */ /* count:1,far,delay_lib.obj */
/* #pragma callt delay_lib_us */ /* count:1,far,delay_lib.obj */
/* #pragma callt delay_lib_ms */ /* count:1,far,delay_lib.obj */
/* #pragma callt delay_lib_s */ /* count:1,far,delay_lib.obj */
/* #pragma callt ms1022_spi_lib_time_tick_init */ /* count:1,far,ms1022_lib.obj */
/* #pragma callt ms1022_spi_lib_int_flag_set */ /* count:1,far,ms1022_lib.obj */
/* #pragma callt ms1022_spi_lib_mhw_it_irq_handle */ /* count:1,far,ms1022_lib.obj */
/* #pragma callt ms1022_spi_lib_read_reg */ /* count:1,far,ms1022_lib.obj */
/* #pragma callt ms1022_spi_lib_send_cmd */ /* count:1,far,ms1022_lib.obj */
/* #pragma callt ms1022_spi_lib_read_reg_state */ /* count:1,far,ms1022_lib.obj */
/* #pragma callt ms1022_spi_lib_read_reg_pw1st */ /* count:1,far,ms1022_lib.obj */
/* #pragma callt ms1022_spi_lib_comm_test */ /* count:1,far,ms1022_lib.obj */
/* #pragma callt ms1022_spi_lib_read_temperature */ /* count:1,far,ms1022_lib.obj */
/* #pragma callt ms1022_spi_task_int_flag_set */ /* count:1,far,ms1022_task.obj */
/* #pragma callt ms1022_spi_task_mhw_it_irq_handle */ /* count:1,far,ms1022_task.obj */
/* #pragma callt ms1022_spi_task_read_temperature */ /* count:1,far,ms1022_task.obj */
/* #pragma callt gpio_lib_init */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_time_tick_init */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_mode_input */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_mode_output */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_mode_pull_up_set */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_mode_pull_up_reset */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_mode_input_normal */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_mode_input_ttl */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_mode_output_normal */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_mode_output_od */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_mode_digital */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_mode_analog */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_mode_ior_set */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_mode_ior_reset */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_set */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_set */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_reset */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_reset */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_toggle */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_toggle */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_pin_read */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_read */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_set_wait_time */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_reset_wait_time */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_toggle_wait_time */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_lib_read_level_wait */ /* count:1,far,gpio_lib.obj */
/* #pragma callt gpio_task_init */ /* count:1,far,gpio_task.obj */
/* #pragma callt gpio_task_pin_mode_ior_set */ /* count:1,far,gpio_task.obj */
/* #pragma callt gpio_task_read_level_wait */ /* count:1,far,gpio_task.obj */
/* #pragma callt crc_enable */ /* count:1,far,crc_cfg.obj */
/* #pragma callt crc_lib_time_tick_init */ /* count:1,far,crc_lib.obj */
/* #pragma callt crc_lib_init */ /* count:1,far,crc_lib.obj */
/* #pragma callt crc_lib_enable */ /* count:1,far,crc_lib.obj */
/* #pragma callt crc_lib_crc32 */ /* count:1,far,crc_lib.obj */
/* #pragma callt crc_lib_check_sum_normal */ /* count:1,far,crc_lib.obj */
/* #pragma callt crc_lib_check_sum_special */ /* count:1,far,crc_lib.obj */
/* #pragma callt my_crc_lib_init */ /* count:1,far,crc_lib.obj */
/* #pragma callt crc_task_init */ /* count:1,far,crc_task.obj */
/* #pragma callt uart_lib_send_reset */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_read_reset */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_read_end */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_init */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_it_irq_read_handle */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_it_irq_read_error_handle */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_it_irq_send_handle */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_it_irq_read_handle_one */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_it_irq_read_error_handle_one */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_it_irq_send_handle_one */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_it_irq_read_handle_two */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_it_irq_read_error_handle_two */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_it_irq_send_handle_two */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_it_irq_read_handle_three */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_it_irq_read_error_handle_three */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_it_irq_send_handle_three */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_fill_mode_send_one */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_fill_mode_send_two */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_fill_mode_send_three */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_fill_mode_send */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_fill_mode_send_start_one */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_fill_mode_send_start_two */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_fill_mode_send_start_three */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_fill_mode_send_start */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_lib_printf_log */ /* count:1,far,uart_lib.obj */
/* #pragma callt uart_task_it_irq_read_handle_two */ /* count:1,far,uart_task.obj */
/* #pragma callt uart_task_it_irq_read_error_handle_two */ /* count:1,far,uart_task.obj */
/* #pragma callt uart_task_it_irq_send_handle_two */ /* count:1,far,uart_task.obj */
/* #pragma callt uart_task_it_irq_read_handle_three */ /* count:1,far,uart_task.obj */
/* #pragma callt uart_task_it_irq_read_error_handle_three */ /* count:1,far,uart_task.obj */
/* #pragma callt uart_task_it_irq_send_handle_three */ /* count:1,far,uart_task.obj */
/* #pragma callt wdt_restart */ /* count:1,far,wdt_cfg.obj */
/* #pragma callt wdt_lib_init */ /* count:1,far,wdt_lib.obj */
/* #pragma callt wdt_lib_restart */ /* count:1,far,wdt_lib.obj */
/* #pragma callt sys_tick_lib_init */ /* count:1,far,sys_tick_lib.obj */
/* #pragma callt sys_tick_lib_it_irq_handle */ /* count:1,far,sys_tick_lib.obj */
/* #pragma callt sys_tick_lib_get_inc_ovf */ /* count:1,far,sys_tick_lib.obj */
/* #pragma callt sys_tick_lib_get_inc_count */ /* count:1,far,sys_tick_lib.obj */
/* #pragma callt sys_tick_lib_get_tick */ /* count:1,far,sys_tick_lib.obj */
/* #pragma callt sys_tick_lib_wait_ms */ /* count:1,far,sys_tick_lib.obj */
/* #pragma callt sys_tick_lib_wait_s */ /* count:1,far,sys_tick_lib.obj */
/* #pragma callt sys_tick_task_init */ /* count:1,far,sys_tick_task.obj */
/* #pragma callt sys_tick_task_it_irq_handle */ /* count:1,far,sys_tick_task.obj */
/* #pragma callt sys_tick_task_get_inc_count */ /* count:1,far,sys_tick_task.obj */
/* #pragma callt sys_tick_task_wait_ms */ /* count:1,far,sys_tick_task.obj */
/* #pragma callt sys_tick_task_wait_s */ /* count:1,far,sys_tick_task.obj */
/* #pragma callt spi_lib_time_tick_init */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_mhw_gpio_init */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_gpio_init */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_gpio_deinit */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_send_msb_byte */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_send_msb_byte_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_read_msb_byte_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_send_msb_word */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_read_msb_word */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_send_msb_word_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_read_msb_word_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_msb_word_cmd */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_msb_word */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_send_lsb_byte */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_lsb_byte */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_send_lsb_byte_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_read_lsb_byte_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_send_lsb_word */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_read_lsb_word */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_send_lsb_word_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_read_lsb_word_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_lsb_word_cmd */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_lsb_word */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_mhw_it_irq_handle */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_task_time_tick_init */ /* count:1,far,spi_task.obj */
/* #pragma callt spi_task_mhw_gpio_init */ /* count:1,far,spi_task.obj */
/* #pragma callt spi_task_msw_gpio_init */ /* count:1,far,spi_task.obj */
/* #pragma callt rl78_clear_reset_flag */ /* count:1,far,rl78_cfg.obj */
/* #pragma callt ms1022_spi_int_flag_set */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt sys_tick_get_inc_count */ /* count:1,far,sys_tick_cfg.obj */
/* #pragma callt spi_mhw_gpio_init */ /* count:1,far,spi_cfg.obj */
/* #pragma callt sys_tick_get_inc_ovf */ /* count:1,far,sys_tick_cfg.obj */
/* #pragma callt sys_tick_get_tick */ /* count:1,far,sys_tick_cfg.obj */
/* #pragma callt at24cxx_i2c_send_page_byte */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt at24cxx_i2c_send_byte */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt at24cxx_i2c_read_page_byte */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt at24cxx_i2c_read_byte */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt at24cxx_task_sw_i2c_send_page_byte */ /* count:1,far,at24cxx_task.obj */
/* #pragma callt delay_tick_ms */ /* count:1,far,delay_cfg.obj */
/* #pragma callt delay_tick_s */ /* count:1,far,delay_cfg.obj */
/* #pragma callt rl78_pclbuz_start */ /* count:1,far,rl78_cfg.obj */
/* #pragma callt at24cxx_lib_i2c_send_page_byte */ /* count:1,far,at24cxx_lib.obj */
/* #pragma callt at24cxx_lib_i2c_send_byte */ /* count:1,far,at24cxx_lib.obj */
/* #pragma callt at24cxx_lib_i2c_read_page_byte */ /* count:1,far,at24cxx_lib.obj */
/* #pragma callt at24cxx_lib_i2c_read_byte */ /* count:1,far,at24cxx_lib.obj */
/* #pragma callt at24cxx_task_i2c_read_byte */ /* count:1,far,at24cxx_task.obj */
/* #pragma callt spi_lib_msw_msb_byte_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_msb_word_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_lsb_byte_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_msw_lsb_word_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_lib_mhw_it_byte_buffer */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_task_msw_msb_byte_buffer */ /* count:1,far,spi_task.obj */
/* #pragma callt gpio_pin_mode_ior_set */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_pin_mode_ior_reset */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_read_level_wait */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_set */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_reset */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_toggle */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt ms1022_spi_lib_send_reg */ /* count:1,far,ms1022_lib.obj */
/* #pragma callt gpio_lib_read_level_wait_time */ /* count:1,far,gpio_lib.obj */
/* #pragma callt crc_lib_crc16_table */ /* count:1,far,crc_lib.obj */
/* #pragma callt crc_lib_crc8_type */ /* count:1,far,crc_lib.obj */
/* #pragma callt crc_lib_check_sum_normal_pos */ /* count:1,far,crc_lib.obj */
/* #pragma callt crc_lib_check_sum_special_pos */ /* count:1,far,crc_lib.obj */
/* #pragma callt crc_lib_check_sum_type */ /* count:1,far,crc_lib.obj */
/* #pragma callt crc_lib_crc16_type */ /* count:1,far,crc_lib.obj */
/* #pragma callt crc_lib_crc16_table_seed_data */ /* count:1,far,crc_lib.obj */
/* #pragma callt hdwinit */ /* count:1,far,main.obj */
/* #pragma callt sys_tick_enable */ /* count:1,far,sys_tick_cfg.obj */
/* #pragma callt at24cxx_i2c_time_tick_init */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt crc_lib_crc8_table */ /* count:1,far,crc_lib.obj */
/* #pragma callt rl78_pclbuz_init */ /* count:1,far,rl78_cfg.obj */
/* #pragma callt gpio_set_wait_time */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_reset_wait_time */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_toggle_wait_time */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt uart_it_irq_read_handle */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_it_irq_read_error_handle */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_it_irq_send_handle */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_fill_mode_send_start */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_printf_log */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_fill_mode_send */ /* count:1,far,uart_cfg.obj */
/* #pragma callt i2c_time_tick_init */ /* count:1,far,i2c_cfg.obj */
/* #pragma callt i2c_lib_msw_init */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_task_msw_init */ /* count:1,far,i2c_task.obj */
/* #pragma callt spi_lib_init */ /* count:1,far,spi_lib.obj */
/* #pragma callt spi_task_init */ /* count:1,far,spi_task.obj */
/* #pragma callt delay_n_ms */ /* count:1,far,delay_cfg.obj */
/* #pragma callt ms1022_spi_read_reg_pw1st */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt ms1022_spi_comm_test */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt spi_time_tick_init */ /* count:1,far,spi_cfg.obj */
/* #pragma callt rl78_port_init */ /* count:1,far,rl78_cfg.obj */
/* #pragma callt ms1022_spi_read_reg */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt gpio_pin_mode_digital */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_pin_mode_analog */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt spi_msw_send_bit_msb_word */ /* count:1,far,spi_cfg.obj */
/* #pragma callt ms1022_spi_time_tick_init */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt spi_msw_send_bit_msb_byte */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_send_bit_lsb_byte */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_send_bit_lsb_word */ /* count:1,far,spi_cfg.obj */
/* #pragma callt rl78_clock_init */ /* count:1,far,rl78_cfg.obj */
/* #pragma callt ms1022_spi_read_reg_state */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt spi_msw_read_bit_lsb_byte */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_read_bit_msb_byte */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_read_bit_msb_word */ /* count:1,far,spi_cfg.obj */
/* #pragma callt gpio_pin_mode_input_normal */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_pin_mode_input_ttl */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_pin_mode_output_normal */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_pin_mode_output_od */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt spi_msw_read_bit_lsb_word */ /* count:1,far,spi_cfg.obj */
/* #pragma callt at24cxx_i2c_init_one */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt at24cxx_lib_i2c_init */ /* count:1,far,at24cxx_lib.obj */
/* #pragma callt at24cxx_task_i2c_init */ /* count:1,far,at24cxx_task.obj */
/* #pragma callt ms1022_spi_lib_init */ /* count:1,far,ms1022_lib.obj */
/* #pragma callt ms1022_spi_task_init */ /* count:1,far,ms1022_task.obj */
/* #pragma callt uart_start_two */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_start_three */ /* count:1,far,uart_cfg.obj */
/* #pragma callt crc_time_tick_init */ /* count:1,far,crc_cfg.obj */
/* #pragma callt my_crc_init */ /* count:1,far,crc_cfg.obj */
/* #pragma callt sys_tick_wait_s */ /* count:1,far,sys_tick_cfg.obj */
/* #pragma callt ms1022_spi_rst */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt spi_msw_msb_word */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_lsb_byte */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_lsb_word */ /* count:1,far,spi_cfg.obj */
/* #pragma callt ms1022_spi_msw_byte_buffer */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt uart_init_two */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_init_three */ /* count:1,far,uart_cfg.obj */
/* #pragma callt i2c_msw_send_cmd */ /* count:1,far,i2c_cfg.obj */
/* #pragma callt i2c_msw_read_bit */ /* count:1,far,i2c_cfg.obj */
/* #pragma callt uart_init */ /* count:1,far,uart_cfg.obj */
/* #pragma callt ms1022_spi_mhw_it_irq_handle */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt spi_mhw_it_irq_handle */ /* count:1,far,spi_cfg.obj */
/* #pragma callt i2c_lib_msw_data_send */ /* count:1,far,i2c_lib.obj */
/* #pragma callt spi_init */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_read_msb_byte_buffer */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_read_msb_word */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_read_lsb_byte_buffer */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_read_lsb_byte */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_read_lsb_word */ /* count:1,far,spi_cfg.obj */
/* #pragma callt sys_tick_it_irq_handle */ /* count:1,far,sys_tick_cfg.obj */
/* #pragma callt spi_msw_send_msb_word */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_send_msb_byte_buffer */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_send_lsb_byte_buffer */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_send_lsb_word */ /* count:1,far,spi_cfg.obj */
/* #pragma callt gpio_pin_mode_pull_up_set */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_pin_mode_pull_up_reset */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt spi_msw_msb_byte_buffer */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_lsb_byte_buffer */ /* count:1,far,spi_cfg.obj */
/* #pragma callt uart_printf_log_two */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_printf_log_three */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_fill_mode_send_buffer_two */ /* count:1,far,uart_cfg.obj */
/* #pragma callt uart_fill_mode_send_buffer_three */ /* count:1,far,uart_cfg.obj */
/* #pragma callt spi_msw_msb_word_buffer */ /* count:1,far,spi_cfg.obj */
/* #pragma callt spi_msw_lsb_word_buffer */ /* count:1,far,spi_cfg.obj */
/* #pragma callt main */ /* count:1,far,main.obj */
/* #pragma callt gpio_pin_mode_input */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt gpio_pin_mode_output */ /* count:1,far,gpio_cfg.obj */
/* #pragma callt i2c_lib_msw_data_read */ /* count:1,far,i2c_lib.obj */
/* #pragma callt i2c_msw_send_word */ /* count:1,far,i2c_cfg.obj */
/* #pragma callt sys_tick_init */ /* count:1,far,sys_tick_cfg.obj */
/* #pragma callt at24cxx_i2c_init */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt i2c_msw_wait_ack */ /* count:1,far,i2c_cfg.obj */
/* #pragma callt R_CSI00_Create */ /* count:1,far,r_cg_sau.obj */
/* #pragma callt ms1022_spi_read_temperature */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt at24cxx_i2c_device_type */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt ms1022_spi_int_flag_wait */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt rl78_init */ /* count:1,far,rl78_cfg.obj */
/* #pragma callt R_UART1_Create */ /* count:1,far,r_cg_sau.obj */
/* #pragma callt i2c_msw_check_device */ /* count:1,far,i2c_cfg.obj */
/* #pragma callt uart_read_end */ /* count:1,far,uart_cfg.obj */
/* #pragma callt spi_gpio_deinit */ /* count:1,far,spi_cfg.obj */
/* #pragma callt R_UART2_Create */ /* count:1,far,r_cg_sau.obj */
/* #pragma callt i2c_msw_init */ /* count:1,far,i2c_cfg.obj */
/* #pragma callt ms1022_spi_config_init */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt app_init */ /* count:1,far,main.obj */
/* #pragma callt sys_tick_wait_ms */ /* count:1,far,sys_tick_cfg.obj */
/* #pragma callt spi_mhw_it_byte_buffer */ /* count:1,far,spi_cfg.obj */
/* #pragma callt crc_check_sum_special_pos */ /* count:1,far,crc_cfg.obj */
/* #pragma callt crc_check_sum_normal_pos */ /* count:1,far,crc_cfg.obj */
/* #pragma callt uart_config_init_three */ /* count:1,far,uart_cfg.obj */
/* #pragma callt spi_msw_gpio_init */ /* count:1,far,spi_cfg.obj */
/* #pragma callt uart_config_init_two */ /* count:1,far,uart_cfg.obj */
/* #pragma callt ms1022_spi_init */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt ms1022_spi_mhw_it_byte_buffer */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt at24cxx_sw_i2c_read_byte */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt ms1022_spi_init_one */ /* count:1,far,ms1022_cfg.obj */
/* #pragma callt at24cxx_sw_i2c_send_byte */ /* count:1,far,at24cxx_cfg.obj */
/* #pragma callt LOG_VA_ARGS */ /* count:0,far,unref,log_cfg.obj */
/* #pragma callt log_printf */ /* count:0,far,unref,log_cfg.obj */
/* #pragma callt log_printf_array */ /* count:0,far,unref,log_cfg.obj */
/* #pragma callt log_printf_string */ /* count:0,far,unref,log_cfg.obj */
/* #pragma callt crc_crc32_hw_reset */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt uart_config_init_one */ /* count:0,far,unref,uart_cfg.obj */
/* #pragma callt uart_fill_mode_send_buffer_one */ /* count:0,far,unref,uart_cfg.obj */
/* #pragma callt uart_printf_log_one */ /* count:0,far,unref,uart_cfg.obj */
/* #pragma callt app_log */ /* count:0,far,unref,main.obj */
/* #pragma callt app_log_args */ /* count:0,far,unref,main.obj */
/* #pragma callt r_adc_interrupt */ /* count:0,near,unref,interrupt,static,r_cg_adc_user.obj */
/* #pragma callt r_comp0_interrupt */ /* count:0,near,unref,interrupt,static,r_cg_comp_user.obj */
/* #pragma callt r_dmac0_interrupt */ /* count:0,near,unref,interrupt,static,r_cg_dmac_user.obj */
/* #pragma callt r_intc0_interrupt */ /* count:0,near,unref,interrupt,static,r_cg_intp_user.obj */
/* #pragma callt r_it_interrupt */ /* count:0,near,unref,interrupt,static,r_cg_it_user.obj */
/* #pragma callt r_wdt_interrupt */ /* count:0,near,unref,interrupt,static,r_cg_wdt_user.obj */
/* #pragma callt at24cxx_i2c_init_two */ /* count:0,far,unref,at24cxx_cfg.obj */
/* #pragma callt at24cxx_i2c_init_three */ /* count:0,far,unref,at24cxx_cfg.obj */
/* #pragma callt ms1022_spi_init_two */ /* count:0,far,unref,ms1022_cfg.obj */
/* #pragma callt ms1022_spi_init_three */ /* count:0,far,unref,ms1022_cfg.obj */
/* #pragma callt crc_crc16_ccitt */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_table_ccitt */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_ccitt_false */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_table_ccitt_false */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_xmodem */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_table_xmodem */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_x25 */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_table_x25 */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_modbus */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_table_modbus */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_ibm */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_table_ibm */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_maxim */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_table_maxim */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_usb */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_table_usb */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_rtu */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_table_rtu */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_dnp */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_table_dnp */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc16_calc_table */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt uart_init_one */ /* count:0,far,unref,uart_cfg.obj */
/* #pragma callt crc_crc32_hw_crc */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc32_table */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc32_mpeg_2 */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc32_table_mpeg_2 */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc32_iso_hdlc */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc32_table_iso_hdlc */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_crc32_table_stm32 */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt R_ADC_Set_OperationOn */ /* count:0,far,unref,r_cg_adc.obj */
/* #pragma callt R_ADC_Set_OperationOff */ /* count:0,far,unref,r_cg_adc.obj */
/* #pragma callt R_DMAC0_Set_SoftwareTriggerOn */ /* count:0,far,unref,r_cg_dmac.obj */
/* #pragma callt R_LCD_Start */ /* count:0,far,unref,r_cg_lcd.obj */
/* #pragma callt R_LCD_Stop */ /* count:0,far,unref,r_cg_lcd.obj */
/* #pragma callt R_LCD_Voltage_On */ /* count:0,far,unref,r_cg_lcd.obj */
/* #pragma callt R_LCD_Voltage_Off */ /* count:0,far,unref,r_cg_lcd.obj */
/* #pragma callt R_PCLBUZ0_Start */ /* count:0,far,unref,r_cg_pclbuz.obj */
/* #pragma callt R_PCLBUZ0_Stop */ /* count:0,far,unref,r_cg_pclbuz.obj */
/* #pragma callt R_WDT_Restart */ /* count:0,far,unref,r_cg_wdt.obj */
/* #pragma callt at24cxx_lib_sw_i2c_send_single_byte */ /* count:0,far,unref,at24cxx_lib.obj */
/* #pragma callt at24cxx_lib_sw_i2c_read_single_byte */ /* count:0,far,unref,at24cxx_lib.obj */
/* #pragma callt at24cxx_task_i2c_time_tick_init */ /* count:0,far,unref,at24cxx_task.obj */
/* #pragma callt at24cxx_task_i2c_deinit */ /* count:0,far,unref,at24cxx_task.obj */
/* #pragma callt at24cxx_task_sw_i2c_send_single_byte */ /* count:0,far,unref,at24cxx_task.obj */
/* #pragma callt at24cxx_task_sw_i2c_read_single_byte */ /* count:0,far,unref,at24cxx_task.obj */
/* #pragma callt at24cxx_task_i2c_send_single_byte */ /* count:0,far,unref,at24cxx_task.obj */
/* #pragma callt at24cxx_task_i2c_read_single_byte */ /* count:0,far,unref,at24cxx_task.obj */
/* #pragma callt i2c_lib_msw_ack */ /* count:0,far,unref,i2c_lib.obj */
/* #pragma callt i2c_lib_msw_nack */ /* count:0,far,unref,i2c_lib.obj */
/* #pragma callt i2c_lib_msw_wait_ack */ /* count:0,far,unref,i2c_lib.obj */
/* #pragma callt i2c_task_msw_send_word */ /* count:0,far,unref,i2c_task.obj */
/* #pragma callt I2CTask_MSW_check_device */ /* count:0,far,unref,i2c_task.obj */
/* #pragma callt i2c_task_msw_send_cmd */ /* count:0,far,unref,i2c_task.obj */
/* #pragma callt i2c_task_msw_data_send */ /* count:0,far,unref,i2c_task.obj */
/* #pragma callt i2c_task_msw_data_read */ /* count:0,far,unref,i2c_task.obj */
/* #pragma callt i2c_task_master_deinit */ /* count:0,far,unref,i2c_task.obj */
/* #pragma callt delay_task_s */ /* count:0,far,unref,delay_task.obj */
/* #pragma callt ms1022_spi_task_time_tick_init */ /* count:0,far,unref,ms1022_task.obj */
/* #pragma callt ms1022_spi_task_read_reg */ /* count:0,far,unref,ms1022_task.obj */
/* #pragma callt ms1022_spi_task_send_cmd */ /* count:0,far,unref,ms1022_task.obj */
/* #pragma callt ms1022_spi_task_read_reg_state */ /* count:0,far,unref,ms1022_task.obj */
/* #pragma callt ms1022_spi_task_read_reg_pw1st */ /* count:0,far,unref,ms1022_task.obj */
/* #pragma callt ms1022_spi_task_comm_test */ /* count:0,far,unref,ms1022_task.obj */
/* #pragma callt gpio_task_time_tick_init */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_pin_mode_pull_up_reset */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_pin_mode_input_normal */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_pin_mode_input_ttl */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_pin_mode_output_normal */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_pin_mode_output_od */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_pin_mode_analog */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_pin_mode_ior_reset */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_set */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_pin_reset */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_reset */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_pin_toggle */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_toggle */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_pin_read */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_read */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_set_wait_time */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_reset_wait_time */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt gpio_task_toggle_wait_time */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt crc_deinit */ /* count:0,far,unref,crc_cfg.obj */
/* #pragma callt crc_task_time_tick_init */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt crc_task_enable */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt crc_task_crc32 */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt crc_task_check_sum_normal */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt crc_task_check_sum_special */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt my_crc_task_init */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt uart_task_send_reset */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_it_irq_read_handle */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_it_irq_read_error_handle */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_it_irq_send_handle */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_it_irq_read_handle_one */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_it_irq_read_error_handle_one */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_it_irq_send_handle_one */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_fill_mode_send_one */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_fill_mode_send_three */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_fill_mode_send */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_fill_mode_send_start_one */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_fill_mode_send_start_two */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_fill_mode_send_start_three */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_fill_mode_send_start */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt uart_task_printf_log */ /* count:0,far,unref,uart_task.obj */
/* #pragma callt wdt_task_init */ /* count:0,far,unref,wdt_task.obj */
/* #pragma callt sys_tick_task_get_inc_ovf */ /* count:0,far,unref,sys_tick_task.obj */
/* #pragma callt spi_task_gpio_deinit */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_send_msb_byte */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_read_msb_byte */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_send_msb_byte_buffer */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_read_msb_byte_buffer */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_send_msb_word */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_read_msb_word */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_send_msb_word_buffer */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_read_msb_word_buffer */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_msb_word_cmd */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_msb_word */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_send_lsb_byte */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_lsb_byte */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_send_lsb_byte_buffer */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_read_lsb_byte_buffer */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_send_lsb_word */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_read_lsb_word */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_send_lsb_word_buffer */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_read_lsb_word_buffer */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_lsb_word_cmd */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_lsb_word */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_mhw_it_irq_handle */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt R_CGC_Get_ResetSource */ /* count:0,far,unref,r_cg_cgc_user.obj */
/* #pragma callt ms1022_spi_int_flag_clear */ /* count:0,far,unref,ms1022_cfg.obj */
/* #pragma callt R_ADC_Get_Result */ /* count:0,far,unref,r_cg_adc.obj */
/* #pragma callt R_INTC0_Start */ /* count:0,far,unref,r_cg_intp.obj */
/* #pragma callt R_INTC0_Stop */ /* count:0,far,unref,r_cg_intp.obj */
/* #pragma callt R_ADC_Start */ /* count:0,far,unref,r_cg_adc.obj */
/* #pragma callt R_ADC_Stop */ /* count:0,far,unref,r_cg_adc.obj */
/* #pragma callt spi_lib_msw_msb_byte */ /* count:0,far,unref,spi_lib.obj */
/* #pragma callt spi_task_msw_msb_byte */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt rl78_pclbuz_stop */ /* count:0,far,unref,rl78_cfg.obj */
/* #pragma callt at24cxx_lib_sw_i2c_send_page_byte */ /* count:0,far,unref,at24cxx_lib.obj */
/* #pragma callt at24cxx_lib_sw_i2c_read_page_byte */ /* count:0,far,unref,at24cxx_lib.obj */
/* #pragma callt at24cxx_task_sw_i2c_read_page_byte */ /* count:0,far,unref,at24cxx_task.obj */
/* #pragma callt at24cxx_task_i2c_send_page_byte */ /* count:0,far,unref,at24cxx_task.obj */
/* #pragma callt at24cxx_task_i2c_send_byte */ /* count:0,far,unref,at24cxx_task.obj */
/* #pragma callt at24cxx_task_i2c_read_page_byte */ /* count:0,far,unref,at24cxx_task.obj */
/* #pragma callt spi_task_msw_msb_word_buffer */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_lsb_byte_buffer */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_msw_lsb_word_buffer */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt spi_task_mhw_it_byte_buffer */ /* count:0,far,unref,spi_task.obj */
/* #pragma callt rl78_adc_clock */ /* count:0,far,unref,rl78_cfg.obj */
/* #pragma callt rl78_i2c1_clock */ /* count:0,far,unref,rl78_cfg.obj */
/* #pragma callt R_COMP0_Stop */ /* count:0,far,unref,r_cg_comp.obj */
/* #pragma callt bcd_to_dec */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt R_IT_Start */ /* count:0,far,unref,r_cg_it.obj */
/* #pragma callt R_IT_Stop */ /* count:0,far,unref,r_cg_it.obj */
/* #pragma callt R_DMAC0_Start */ /* count:0,far,unref,r_cg_dmac.obj */
/* #pragma callt ms1022_spi_task_send_reg */ /* count:0,far,unref,ms1022_task.obj */
/* #pragma callt gpio_task_read_level_wait_time */ /* count:0,far,unref,gpio_task.obj */
/* #pragma callt crc_task_crc16_table */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt crc_task_crc8_type */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt crc_task_check_sum_normal_pos */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt crc_task_check_sum_special_pos */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt crc_task_check_sum_type */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt crc_task_crc16_type */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt crc_task_crc16_table_seed_data */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt R_SAU1_Create */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt R_TAU0_Channel2_Start */ /* count:0,far,unref,r_cg_tau.obj */
/* #pragma callt R_TAU0_Channel2_Stop */ /* count:0,far,unref,r_cg_tau.obj */
/* #pragma callt sys_tick_disable */ /* count:0,far,unref,sys_tick_cfg.obj */
/* #pragma callt R_WDT_Create */ /* count:0,far,unref,r_cg_wdt.obj */
/* #pragma callt ms1022_spi_fosc_disable */ /* count:0,far,unref,ms1022_cfg.obj */
/* #pragma callt ms1022_spi_fosc_enable */ /* count:0,far,unref,ms1022_cfg.obj */
/* #pragma callt rl78_sau1_clock */ /* count:0,far,unref,rl78_cfg.obj */
/* #pragma callt rl78_sau2_clock */ /* count:0,far,unref,rl78_cfg.obj */
/* #pragma callt R_DMAC0_Stop */ /* count:0,far,unref,r_cg_dmac.obj */
/* #pragma callt R_RTC_Create */ /* count:0,far,unref,r_cg_rtc.obj */
/* #pragma callt R_SAU0_Create */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt crc_task_crc8_table */ /* count:0,far,unref,crc_task.obj */
/* #pragma callt delay_n_s */ /* count:0,far,unref,delay_cfg.obj */
/* #pragma callt R_UART1_Receive */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt R_CSI00_Stop */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt R_UART2_Receive */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt hex_to_ascii */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt compare_byte */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt R_IT_Create */ /* count:0,far,unref,r_cg_it.obj */
/* #pragma callt R_PORT_Create */ /* count:0,far,unref,r_cg_port.obj */
/* #pragma callt uart_interrupt_receive_two */ /* count:0,near,unref,interrupt,static,r78_it.obj */
/* #pragma callt uart_interrupt_receive_error_two */ /* count:0,near,unref,interrupt,static,r78_it.obj */
/* #pragma callt uart_interrupt_send_two */ /* count:0,near,unref,interrupt,static,r78_it.obj */
/* #pragma callt uart_interrupt_receive_three */ /* count:0,near,unref,interrupt,static,r78_it.obj */
/* #pragma callt uart_interrupt_receive_error_three */ /* count:0,near,unref,interrupt,static,r78_it.obj */
/* #pragma callt uart_interrupt_send_three */ /* count:0,near,unref,interrupt,static,r78_it.obj */
/* #pragma callt sys_tick_interrupt */ /* count:0,near,unref,interrupt,static,r78_it.obj */
/* #pragma callt ms1022_interrupt_flag */ /* count:0,near,unref,interrupt,static,r78_it.obj */
/* #pragma callt ms1022_interrupt_spi */ /* count:0,near,unref,interrupt,static,r78_it.obj */
/* #pragma callt compare_word */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt R_COMP0_Start */ /* count:0,far,unref,r_cg_comp.obj */
/* #pragma callt dec_to_bcd */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt R_PCLBUZ0_Create */ /* count:0,far,unref,r_cg_pclbuz.obj */
/* #pragma callt ascii_to_hex */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt swap_bit_uint8 */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt R_DMAC0_Create */ /* count:0,far,unref,r_cg_dmac.obj */
/* #pragma callt R_UART1_Stop */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt R_UART2_Stop */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt uart_stop_two */ /* count:0,far,unref,uart_cfg.obj */
/* #pragma callt uart_stop_three */ /* count:0,far,unref,uart_cfg.obj */
/* #pragma callt R_CSI00_Start */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt hex_to_bcd */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt R_CGC_Create */ /* count:0,far,unref,r_cg_cgc.obj */
/* #pragma callt R_UART1_Send */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt R_UART2_Send */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt compare_byte_to_byte */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt R_UART1_Start */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt R_UART2_Start */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt compare_byte_to_byte_from_index */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt my_str_cmp */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt compare_word_to_word */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt compare_word_to_word_from_index */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt spi_msw_msb_byte */ /* count:0,far,unref,spi_cfg.obj */
/* #pragma callt R_RTC_Start */ /* count:0,far,unref,r_cg_rtc.obj */
/* #pragma callt R_RTC_Stop */ /* count:0,far,unref,r_cg_rtc.obj */
/* #pragma callt my_str_cmp_index */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt R_CSI00_Send_Receive */ /* count:0,far,unref,r_cg_sau.obj */
/* #pragma callt R_INTC_Create */ /* count:0,far,unref,r_cg_intp.obj */
/* #pragma callt desc_sort_word */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt rl78_perpheral_clock_disable */ /* count:0,far,unref,rl78_cfg.obj */
/* #pragma callt invert_uint8 */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt ascii_to_utf8_array */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt invert_uint16 */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt desc_sort_byte */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt my_pow */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt asc_sort_word */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt asc_sort_byte */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt my_str_n_str */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt calc_avg_word */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt calc_avg_byte */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt R_COMP_Create */ /* count:0,far,unref,r_cg_comp.obj */
/* #pragma callt R_ADC_Create */ /* count:0,far,unref,r_cg_adc.obj */
/* #pragma callt delay_1us */ /* count:0,far,unref,delay_cfg.obj */
/* #pragma callt calc_avg_byte_from_index */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt calc_avg_word_from_index */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt calc_avg_double_word_from_index */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt asc_sort_double_word */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt spi_msw_bit_msb_byte_clock_pulse */ /* count:0,far,unref,spi_cfg.obj */
/* #pragma callt spi_msw_bit_msb_word_clock_pulse */ /* count:0,far,unref,spi_cfg.obj */
/* #pragma callt spi_msw_bit_lsb_byte_clock_pulse */ /* count:0,far,unref,spi_cfg.obj */
/* #pragma callt spi_msw_bit_lsb_word_clock_pulse */ /* count:0,far,unref,spi_cfg.obj */
/* #pragma callt R_TAU0_Create */ /* count:0,far,unref,r_cg_tau.obj */
/* #pragma callt my_itoa */ /* count:0,far,unref,complier_lib.obj */
/* #pragma callt R_RTC_Get_CounterValue */ /* count:0,far,unref,r_cg_rtc.obj */
/* #pragma callt R_RTC_Set_CounterValue */ /* count:0,far,unref,r_cg_rtc.obj */
/* #pragma callt rtc_calc_week */ /* count:0,far,unref,rtc_cfg.obj */
/* #pragma callt R_LCD_Create */ /* count:0,far,unref,r_cg_lcd.obj */

